services:
  - type: web
    name: odoo-web
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: HOST
        fromService:
          type: pserv
          name: odoo-db
          property: host
      - key: USER
        value: odoo
      - key: PASSWORD
        fromService:
          type: pserv
          name: odoo-db
          property: password
      - key: PORT
        value: "5432"
      - key: DATABASE
        value: odoo
      - key: ODOO_ADMIN_PASSWORD
        value: admin

databases:
  - name: odoo-db
    databaseName: odoo
    user: odoo
